### PR TITLE
refactor: structure

### PR DESCRIPTION
**Pull request by MartinBernstorff**
New structure is:
```
src/psycop_model_evaluation
├── binary_classification
│   ├── plots
│   │   ├── base_charts.py
│   │   ├── feature_importance
│   │   │   ├── shap
│   │   │   └── sklearn
│   │   │       └── feature_importance.py
│   │   ├── global_performance
│   │   │   ├── precision_recall.py
│   │   │   └── roc_auc.py
│   │   ├── robustness
│   │   │   ├── subgroups
│   │   │   │   ├── performance_by_age.py
│   │   │   │   ├── performance_by_input.py
│   │   │   │   └── performance_by_sex.py
│   │   │   └── time
│   │   │       ├── cyclic
│   │   │       │   ├── data_by_cyclic_time.py
│   │   │       │   └── plot_by_cyclic_time.py
│   │   │       └── linear
│   │   │           ├── absolute
│   │   │           │   ├── data_by_absolute_time.py
│   │   │           │   ├── plot_by_absolute_time.py
│   │   │           │   └── prob_over_time.py
│   │   │           └── timedelta
│   │   │               ├── data_by_timedelta.py
│   │   │               └── plot_by_timedelta.py
│   │   └── utils.py
│   └── tables
│       ├── descriptive_stats_table.py
│       ├── feature_importance.py
│       ├── output_table.py
│       └── performance_by_threshold.py
└── utils.py
```

Would love feedback on the structure! On the one hand, it means we get pretty long imports like:

```
from psycop_model_evaluation.binary_classification.plots.robustness.time.linear.timedelta.data_by_timedelta import (
    create_sensitivity_by_time_to_outcome_df,
)
```

On the other hand, I feel like it makes it way easier to find the correct spot for a new plot. 

My current impression is that I might've gone a bit too deep on the nesting. One compromise here would be to collapse all the folders, e.g. timedelta, into one file - timedelta.py.

What do you guys think?

### CODE REVIEW

**Comment by MartinBernstorff** [comment]
Pinging @HLasse, @bokajgd, @signekb, @sarakolding – would love some comments on this! I expect you guys to be the primary users 👍

**Comment by MartinBernstorff** [comment]
A flatter, alternative structure:
```
src/psycop_model_evaluation
├── binary_classification
│   ├── data_processing
│   │   ├── feature_importance
│   │   │   ├── shap.py
│   │   │   └── sklearn.py
│   │   ├── global_performance
│   │   │   ├── precision_recall.py
│   │   │   └── roc_auc.py
│   │   ├── robustness
│   │   │   ├── subgroups
│   │   │   │   ├── age.py
│   │   │   │   ├── input.py
│   │   │   │   └── sex.py
│   │   │   └── time
│   │   │       ├── cyclic.py
│   │   │       ├── linear_absolute.py
│   │   │       └── linear_timedelta.py
│   │   └── utils.py
│   ├── plots
│   │   ├── base_charts.py
│   │   ├── feature_importance.py
│   │   ├── global_performance.py
│   │   ├── robustness.py
│   │   └── utils.py
│   └── tables
│       ├── descriptive_stats.py
│       ├── feature_importance.py
│       ├── output.py
│       ├── performance_by_threshold.py
│       └── utils.py
└── utils.py
```

**Comment by signekb** [comment]
Looks great! Intuitively, I'm more pro the flatter structure 😊

**Comment by KennethEnevoldsen** [comment]
So as we talked about I would probably suggest the structure:

```
src/psycop_model_evaluation
├─ binary_classification
│   ├── feature_importance
│   │   ├─ plots.py
│   │   ├─ tables.py
│   │   └── utils.py # includes data processing for feature importance
│   ├─ ...
├── ...
```

After thinking about it I would probably even change it to:
```
src/psycop_model_evaluation
├─  feature_importance
│   ├── binary classification # potentially just remove this one
│   │   ├─ plots.py
│   │   ├─ tables.py
│   │   └── utils.py
│   ├─ ...
├── ...
```

But I don't have a strong preference on either of these two though, but I believe it is better for

**Pull request merged**
